[package]
name = "hello_world"
version = "0.1.0"
authors = ["yangpei <yangpei11@pku.edu.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra-glm = "0.3"
